version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x64
- x86
build:
  project: build\X12Lib.sln
  verbosity: minimal
  parallel: true
notifications:
- provider: Email
  to:
  - k-payl@yandex.ru
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false