version: 1.0.{build}
branches:
  except:
    - gh-pages
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x64
- x86
install:
- git submodule update --init --recursive
- ps: Start-FileDownload 'https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe'
- cmd: vulkan_sdk.exe /S
- cmd: set VULKAN_SDK=C:\VulkanSDK\1.2.135.0
build_script:
    - mkdir build
    - cd build
    - cmake %CMAKE_CONFIGURE_FLAGS% ../
    - cmake --build . %CMAKE_BUILD_FLAGS%
notifications:
- provider: Email
  to:
  - k-payl@yandex.ru
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false