name: Benchmark
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Vector math benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run
        run: cd src/benchmarks && make json
      - name: Store result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: src/benchmarks/benchmark_result.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          alert-comment-cc-users: '@k-payl'
          max-items-in-chart: 30

      #- uses: lukka/run-cmake@v3
      #  with:
      #    cmakeGenerator: VS16Win64
      #    cmakeListsOrSettingsJson: CMakeListsTxtBasic
      #    cmakeListsTxtPath: ${{ github.workspace }}\CMakeLists.txt
      #    cmakeBuildType: Release
      #    buildDirectory: ${{ github.workspace }}\build
      #    buildWithCMake: true
      #
      #- name: Run test
      #  run: cd build && Release\\tests.exe --gtest_catch_exceptions=0
      #  shell: cmd
